IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Clients')
BEGIN
	CREATE TABLE Clients (
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		PublicKey NVARCHAR(30) NOT NULL,
		SecretKey NVARCHAR(30) NOT NULL,
		Descripcion NVARCHAR (60) NOT NULL,
		Hosts NVARCHAR(max) NOT NULL,
		AccesTokenExp NUMERIC NOT NULL,
		RefreshTokenExp	NUMERIC NOT NULL,
		IsActive BIT DEFAULT 1
		)
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Resources')
BEGIN
	CREATE TABLE Resources (
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		Descripcion NVARCHAR(60) NOT NULL,
		IsActive BIT DEFAULT 1
	)
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Catalogs')
BEGIN
	CREATE TABLE Catalogs(
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		CatalogType NVARCHAR(30) NOT NULL, --Scope
		CatalogValue NVARCHAR(30) NOT NULL, --Read, Write, Update, Delete, Admin
		Descripcion NVARCHAR(60) NOT NULL, --Permite Leer, Permite escribir, Permite editar, Todos los permisos
		IsActive BIT DEFAULT 1
	)
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ResourceClientPermissions')
BEGIN
	CREATE TABLE ResourceClientPermissions (
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		ClientId UNIQUEIDENTIFIER NOT NULL,
		ResourceId UNIQUEIDENTIFIER NOT NULL,
		ScopeId UNIQUEIDENTIFIER NOT NULL,
		IsActive BIT DEFAULT 1
	)

	ALTER TABLE ResourceClientPermissions
	ADD CONSTRAINT FK_Permissions_Resources FOREIGN KEY (ResourceId) REFERENCES Resources(Id);

	ALTER TABLE ResourceClientPermissions
	ADD CONSTRAINT FK_Permissions_Client FOREIGN KEY (ClientId) REFERENCES Clients(Id);

	ALTER TABLE ResourceClientPermissions
	ADD CONSTRAINT FK_Permissions_Scope FOREIGN KEY (ScopeId) REFERENCES Catalogs(Id);
END


IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Authorizations')
BEGIN
	CREATE TABLE Authorizations (
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		PermissionsId UNIQUEIDENTIFIER NOT NULL,
		AuthorizationToken NVARCHAR(max) NOT NULL,
		RefreshToken NVARCHAR(max) NOT NULL,
		IsActive BIT DEFAULT 1
	)

	ALTER TABLE Authorizations
	ADD CONSTRAINT FK_Authorizations_Permissions FOREIGN KEY (PermissionsId) REFERENCES ResourceClientPermissions(Id);
END