IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Clients')
BEGIN
	CREATE TABLE Clients (
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		Descripcion NVARCHAR (60) NOT NULL
		)
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Resources')
BEGIN
	CREATE TABLE Resources (
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		ClientId UNIQUEIDENTIFIER NOT NULL,
		PublicKey NVARCHAR(30) NOT NULL,
		SecretKey NVARCHAR(30) NOT NULL,
		IsActive BIT DEFAULT 1,
		[Type]	NVARCHAR(30) NOT NULL,
		Descripcion NVARCHAR(60) NOT NULL,
		Hosts NVARCHAR(max) NOT NULL,
		AccesTokenExp NUMERIC NOT NULL,
		RefreshTokenExp	NUMERIC NOT NULL
	)

	ALTER TABLE Resources
	ADD CONSTRAINT FK_Resources_Clients FOREIGN KEY (ClientId) REFERENCES Clients(Id);
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Authorizations')
BEGIN
	CREATE TABLE Authorizations (
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		ResourceId UNIQUEIDENTIFIER NOT NULL,
		AccesToken NVARCHAR(max) NOT NULL,
		RefreshToken NVARCHAR(max) NOT NULL,
		IsActive BIT DEFAULT 1
	)

	ALTER TABLE Authorizations
	ADD CONSTRAINT FK_Authorizations_Resources FOREIGN KEY (ResourceId) REFERENCES Resources(Id);
END